// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Reading struct {
	ID                  int64           `json:"id"`
	SensorID            string          `json:"sensor_id"`
	RecordedAt          int64           `json:"recorded_at"`
	TemperatureCelsius  sql.NullFloat64 `json:"temperature_celsius"`
	HumidityPercent     sql.NullFloat64 `json:"humidity_percent"`
	SoilMoisturePercent sql.NullFloat64 `json:"soil_moisture_percent"`
}
