// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const insertReading = `-- name: InsertReading :one
INSERT INTO readings (sensor_id, recorded_at, temperature_celsius, humidity_percent, soil_moisture_percent)
VALUES (?, ?, ?, ?, ?)
RETURNING id, sensor_id, recorded_at, temperature_celsius, humidity_percent, soil_moisture_percent
`

type InsertReadingParams struct {
	SensorID            string          `json:"sensor_id"`
	RecordedAt          int64           `json:"recorded_at"`
	TemperatureCelsius  sql.NullFloat64 `json:"temperature_celsius"`
	HumidityPercent     sql.NullFloat64 `json:"humidity_percent"`
	SoilMoisturePercent sql.NullFloat64 `json:"soil_moisture_percent"`
}

func (q *Queries) InsertReading(ctx context.Context, arg InsertReadingParams) (Reading, error) {
	row := q.db.QueryRowContext(ctx, insertReading,
		arg.SensorID,
		arg.RecordedAt,
		arg.TemperatureCelsius,
		arg.HumidityPercent,
		arg.SoilMoisturePercent,
	)
	var i Reading
	err := row.Scan(
		&i.ID,
		&i.SensorID,
		&i.RecordedAt,
		&i.TemperatureCelsius,
		&i.HumidityPercent,
		&i.SoilMoisturePercent,
	)
	return i, err
}

const listReadings = `-- name: ListReadings :many
SELECT id, sensor_id, recorded_at, temperature_celsius, humidity_percent, soil_moisture_percent FROM readings ORDER BY recorded_at DESC LIMIT ?
`

func (q *Queries) ListReadings(ctx context.Context, limit int64) ([]Reading, error) {
	rows, err := q.db.QueryContext(ctx, listReadings, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.SensorID,
			&i.RecordedAt,
			&i.TemperatureCelsius,
			&i.HumidityPercent,
			&i.SoilMoisturePercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
